apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-admission.postgresServiceName" . }}
  labels:
    {{- include "student-admission.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "student-admission.postgresName" . }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  clusterIP: None  # Headless for StatefulSet DNS
