apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-admission.appName" . }}-svc
  labels:
    {{- include "student-admission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "student-admission.appName" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      name: http
